### PR TITLE
Add/update healthcheck in launch config

### PR DESCRIPTION
**Pull request by rgarcia**
For context, see https://clever.atlassian.net/browse/INFRA-867.

This PR was autogenerated by pulling the config for the load balancer that this repo is connected to in prod. @mohit please review that the changes here are correct.

### CODE REVIEW

**Comment by rgarcia** [comment]
@mohit build failing due to backwards-incompatible dependency change

**Comment by rgarcia** [comment]
(plus lack of dependency locking)

**Comment by rgarcia** [comment]
@mohit bump this is the last remaining PR for INFRA-867

**Comment by mohit** [comment]
merging, since tests are :+1:

**Pull request merged**
